version: '3.8'

services:
  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: YourNewStrongPassword
      MYSQL_DATABASE: email_signal_processing
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - "3306:3306"

  app:
    build: .
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
      - temporal

  temporal:
    image: temporalio/auto-setup:latest
    container_name: temporal
    environment:
      - DB=mysql8
      - MYSQL_USER=root
      - MYSQL_PWD=YourNewStrongPassword
      - MYSQL_SEEDS=db
    depends_on:
      - db
    ports:
      - "7233:7233" 

  worker:
    build:
      context: .
      dockerfile: Dockerfile.worker  
    command: bash -c "python temporal/wait_for_db.py && python temporal/worker.py"
    environment:
      - TEMPORAL_HOST=temporal
      - TEMPORAL_PORT=7233
      - DB_HOST=db
      - DB_PORT=3306
      - DB_USER=root
      - DB_PASSWORD=YourNewStrongPassword
      - DB_NAME=email_signal_processing
    volumes:
      - .:/app
    depends_on:
      - db
      - temporal

volumes:
  db_data:
